server:
  port: 8088
  servlet:
    session:
      cookie:
        name: u_id
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/manage?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml

logging:
  level:
    com.baomidou.mybatisplus.samples: debug