server:
  port: 8088
  servlet:
    session:
      cookie:
        name: u_id
# 数据库连接
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/manage?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  mvc:
    static-path-pattern: /upload
  resources:
    static-locations: file:${my-file.upload.url}
# 寻找mapper.xml文件
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml

logging:
  level:
    com.baomidou.mybatisplus.samples: debug

# 文件上传路径
my-file:
  upload:
    url: E:\upload
    prefix: /upload